### ISSUE TITLE
Controlling tag inheritance

### ISSUE THREAD

**Issue by ATizK** [eyeinsky/org-anki#100]
Hi, here is a feature that may be useful : a fine-grained control on tag inheritance between org and anki.

In my case, I would essentially use it to exclude tags that are useful for writing / organisational purposes inside org, but are useless in anki (and in my case a bit distracting as I do display the Tags field in my anki cards).

A way I could imagine this work (from a maybe very naive perspective) would be to set a list of excluded (maybe "allowed" could be relevant as well) tags, as an alternative to full inheritance.

Also, thanks for the awesome package and maintenance !

**Comment by eyeinsky** [comment]
Yup, this would be a useful feature, am planning to implement this. (Pull requests also welcome!)
