### ISSUE TITLE
Can't create note when it starts with latex

### ISSUE THREAD

**Issue by 1over137** [eyeinsky/org-anki#107]
It just says "Beginning of buffer" on the messages, no errors reported.

Example
```
*** Dipole moment   
\( \bar{p} = Q\bar{d}\)
where d is the separation vector pointing toward the positive charge
```

**Comment by 1over137** [comment]
This turned out to be an org-mode bug.

**Comment by eyeinsky** [comment]
@1over137 thanks for researching this! Is there a link to the bug?

**Comment by 1over137** [comment]
https://list.orgmode.org/20241125205531.416893-2-dev@notyourcomputer.net/T/#u
