### ISSUE TITLE
Is it possible to sync tags?

### ISSUE THREAD

**Issue by dmitrym0** [eyeinsky/org-anki#14]
Wonderful module; is it possible to sync heading tags as well?

**Comment by eyeinsky** [comment]
At the moment, no. I looked into it hoping it will be quick to implement but it appears that although adding tags when creating a note is straightforward, then changing tags when updating a note [isn't](https://github.com/FooSoft/anki-connect/issues/183).

I'd also like to have this feature but it might take some time until I get to it.

**Comment by eyeinsky** [comment]
Pushed what I had to the `tags` branch. The update part isn't done yet.

**Comment by eyeinsky** [comment]
dd41a6c18d8dc3a14c8e40adce94748266f62de2 (tip of `tags` branch) It's possible to now sync tags, org-mode tags are the source of truth: tags not set for a title are removed and tags not currently present are added.

I still need to figure out allowed characters in Anki vs org-mode (there are differences) and also dependency bounds, but you can play with it if you'd like.

**Comment by eyeinsky** [comment]
> Tags are normal words containing letters, numbers, ‘_’, and ‘@’.
^ https://orgmode.org/guide/Tags.html

Tested all these characters in Anki and since they work pushed a new master with tag synchronization.
