### ISSUE TITLE
Can't update card. ID has type str

### ISSUE THREAD

**Issue by kastidad** [eyeinsky/org-anki#16]
Hi!

Thanks for org-anki, it has allowed to use all the power of emacs to edit _ANY_ org file (unlike anki-editor) & send it to Anki.

But I tend to refine/edit my cards while using them so I've tried to **update** them to no avail. I get this message:

_"org-anki error: Couldn’t update note, received: '1628261282716' has type str, but expected one of: int, long"_

Is there a way to edit already created cards & not just create them?

Thanks!

**Comment by eyeinsky** [comment]
Thanks for reporting! Updates should work as well -- what version of Anki and AnkiConnect are you running?

**Comment by kastidad** [comment]
Hi, Thanks for your response!

I'm actually not sure about a couple of things:

1- You mean Updating the Card is a feature already present in org-anki? ...that for some reason is not working on my end?

Or did I misundestood?

2- How can I find out AnkiConnect version? :) .
I know it's the last one because not long ago it asked for an update and in general I keep all Anki's Add-ons updated.

My version of Anki is 2.1.38 @linux-x64 and I'm using Doom-Emacs latest.

Many thanks!

**Comment by eyeinsky** [comment]
Yes, the feature is already present. I've tried to fix the issue with version 0.0.5 4f2fb3a8f8c3dca2d6d31b7d368120dbb97ec666, please see if it helps!

As for the reason it seems AnkiConnect has added type hints [here](https://github.com/FooSoft/anki-connect/commit/b8a7151ed0015691b57c076456f517a56a07a1ff#diff-3c32c5a21e787c202f5c03bbc7e8fb8a5ab6754dbbcedebab10aa16adf09837dR292), but for me they are not enforced -- I suspect due to the python version used. `python --version` gets me `Python 2.7.18` and `python3 --version` is `Python 3.8.9`, what do you get?

**Comment by kastidad** [comment]
Thank you very much!!!

For some reason when trying to update _org-anki_ through Doom's `~/.emacs.d/bin/doom sync -u` didn't work out well so I checked Melpa in case the update haven't been uploaded there but there it was...

So I just downloaded the new _org-anki.el_ file to replace the old one but still no cigar as it complained about async-await when trying to sync-entry.

In the end I just _(require_-d these 2 new deps so Doom would download them directly and BINGO!
I just added these lines to package.el (this is just for Doom, don't know about other Emacses...):

``` elisp
(package! org-anki)
(package! cl-lib)
(package! async-await)

```

Anyway I tried updating a few cards and it seems to be working Really-Well.

Many thanks again brother!!!

**Comment by kastidad** [comment]
BTW python version is 3.9.5 👍

**Comment by eyeinsky** [comment]
Thanks for reporting the bug!

**Comment by eyeinsky** [comment]
@kastidad I've pushed a new version (v0.0.6) -- if you have time then please check if everything still works for you!

**Comment by kastidad** [comment]
Hi!

Sorry for the delay.

I tested all new functions in v006 and it seems to be working fine. Obviously for the _-all_ functions to work it required the ANKI_DECK line to be on top of the file and not just on each entry. Without that it doesn't work.

Also I tested the _-delete-_ functions and it's working pretty neatly, so GREAT JOB!!!

I hope in the future I could write some emacs app but elisp tutorials don't seem to touch on important details. How do you know which version of Emacs is required and which libraries do you need for writing your app?

Anyway thanks for org-anki and best regards!

**Comment by eyeinsky** [comment]
> How do you know which version of Emacs is required and which libraries do you need for writing your app?

If you mean dependency versions then `package-lint` helps.

But other than that, it's the elisp documentation, and for non-included packages searching melpa and looking at the download numbers.

Another method has been to look at the dependencies of popular packages, e.g if I'm going to depend on org-mode anyway then I might as well use those when needed (when I don't have my own preferences).

But yes, it's not straight-forward to find what you need.

**Comment by kastidad** [comment]
Hi!

I did further testing of v0.0.6 and although it seems to be working fine, it has lost something that was present on previous versions but it's absent now that might be a usability problem.

In previous version(s) when modifying/correcting already created cards, if one has the card open in Anki and modifies its content with Emacs, IMMEDIATELY after syncing you could go back to Anki and notice the change you just made.

But now that change is not reflected UNTIL next time you open the card --whether is while reviewing it again or through the Anki's Browser.

So if one is reviewing/correcting the card and makes some change(s), usually to be sure the change was taken or that one didn't forgot to sync the entry (like making the changes then obliviously forgetting to sync), in the previous version it was just a matter of going back to Anki to notice the changes that were just synced.

Now that change is NOT reflected and one is required to answer the card first (with something like Again, Hard to see it soon), then go through other cards until next time this card is back and ONLY then you can verify your changes.

I don't know if you understand me or if my writing was confusing. Please ask me if that's the case.

I'll try to adapt to this new behaviour as for now I'm memorizing new material so the history and intervals are not long, but I can see that being a problem for material that it's to be reviewed much later than just 1/2 days, in which case I might return to the previous version to not lose the record/history of reviews.

Thanks!

**Comment by eyeinsky** [comment]
This is a known issue and it was present before: having the card browser open messes up using AnkiConnect, so just close it before syncing cards.

The issue is here from that comment onward https://github.com/FooSoft/anki-connect/issues/82#issuecomment-500179245

**Comment by kastidad** [comment]
Hi!

Thanks for your response, but I meant that while having Anki's reviewing interface open, or in other words being in the middle of reviewing the day's decks --I actually don't use the card browser, just very occasionally.

In version 0.0.5, while I was reviewing with Anki, and let's say I have Emacs & Anki side-by-side, when I see that the present Anki card was not optimally formulated, I modified it in Emacs, and having both windows visible, immediately after syncing I would see the change in front of my eyes.

Now with v0.0.6 that's not possible so I have to answer "Again" and ONLY next time the card appears back I could verify my changes, but doing so means losing the history/record for those cards.

Thanks!

**Comment by eyeinsky** [comment]
Hmm, alright. I switched to using the `multi` API call even when updating a single note, but now given this I'll switch back -- thanks for this feedback! Added new issue here #19.
