### ISSUE TITLE
Use plain updateNoteFields when updating a single note

### ISSUE THREAD

**Issue by eyeinsky** [eyeinsky/org-anki#19]
As [reported here](https://github.com/eyeinsky/org-anki/issues/16#issuecomment-904913153) multi doesn't cause a real-time update of note content while reviewing while a plain `updateNoteFields` does.

**Comment by eyeinsky** [comment]
@kastidad Does this also matter when adding notes? I.e when reviewing a deck then new notes used to appear in the deck with the previous version but don't do it now?

**Comment by kastidad** [comment]
Hi!

No, with fresh notes, they correctly appear referenced in the deck while reviewing (the indicator of a _new_ card anyway), but if I keep reviewing I eventually arrive at it.

**Comment by eyeinsky** [comment]
@kastidad Could you try the code in this branch: https://github.com/eyeinsky/org-anki/tree/single-update-without-multi It doesn't use the multi action if there is a single update.

When I tested this for me it doesn't seem to work even now. The test was to study cards and update the one that I'm currently looking at. On what OS and which Anki app are you using?

**Comment by eyeinsky** [comment]
This is now merged to master 04299be37766cf706912b410a88ef3ed1a2e69b6
