### ISSUE TITLE
Anki cards resulting from the org file

### ISSUE THREAD

**Issue by Doxdrum** [eyeinsky/org-anki#2]
@eyeinsky Thank you for sharing this interesting project. I saw that you added a sample file, but it could be useful if you would include some pictures of the resulting anki cards. In particular, exemplifying the role of the different `org` structures in the resulting cards.

**Comment by eyeinsky** [comment]
Good idea, will do. Are screenshots of the cards created from the sample file enough?

**Comment by eyeinsky** [comment]
@Doxdrum See if the ["How" section in this branch](https://github.com/eyeinsky/org-anki/tree/example-screenshots#how) explains how the cards look better?
