### ISSUE TITLE
Missed dependency - promise

### ISSUE THREAD

**Issue by jumper047** [eyeinsky/org-anki#22]
I don't have promise package insalled, and org-anki commands not worked untill I installed it by hands.

**Comment by walseb** [comment]
I have the same problem, I assumed it was a bug in my setup. Looking over this package now it seems like `promise` is missing from the "Package-Requires" section in `org-anki.el` which `straight.el` among others rely on.

**Comment by gsingh93** [comment]
I ran into the same issue. @eyeinsky, can you take a look at this?

**Comment by eyeinsky** [comment]
@gsingh93 could you look if it's ok now?

Discovered that also `dash` was missing from the dependencies. Both of these were installed as dependencies for other packages, so didn't notice.

**Comment by gsingh93** [comment]
Yup, I deleted `org-anki` and `promise`, installed `org-anki`, and `promise` was automatically installed as a dependency and the error was gone. Thanks for the fix!
