### ISSUE TITLE
Allow HTML tags in notes

### ISSUE THREAD

**Issue by gsingh93** [eyeinsky/org-anki#40]
I'm trying to create a note with some line breaks: `* Questions:<br>- {{c1::Item 1}}<br>- {{c2::Item 2}}<br>- {{c3::Item 3}}`

But when I export this, the HTML tags are escaped. Is there an option to add the note without escaping HTML characters so I can have Anki parse my own HTML?

**Comment by pecheny** [comment]
I use anki-editor, facing same issue i made little investigation and have found that html tags escaping is a part of org-mode to html conversion. So [this](https://orgmode.org/manual/Quoting-HTML-tags.html) works for me.

**Comment by eyeinsky** [comment]
This also works for adding custom css for specific notes, thanks @pecheny!
