### ISSUE TITLE
Same-level headings are added to the back of the card

### ISSUE THREAD

**Issue by nmlc** [eyeinsky/org-anki#42]
When calling `org-anki-sync-all` while headings are in folded mode, same-level headings are added to the back of the card.

org-anki version: `1.0.1`
Can be reproduced with this org file:
```
#+ANKI_DECK: test
#+ANKI_MATCH: -ANKI_IGNORE="true"
* heading 1
:PROPERTIES:
:ANKI_IGNORE: true
:END:
** heading 2
:PROPERTIES:
:ANKI_IGNORE: true
:END:
*** heading 3
:PROPERTIES:
:ANKI_IGNORE: true
:END:
**** anki item 1
back
**** anki item 2
back
**** anki item 3
back
```

**Comment by eyeinsky** [comment]
Thank you for reporting! Fixed in latest master (v1.0.2 / [c084599](https://github.com/eyeinsky/org-anki/commit/c084599a199f794b7e25d5ca4d58f0c0ad87c160))
