### ISSUE TITLE
org-anki-skip-function isn't being picked up

### ISSUE THREAD

**Issue by nyxkn** [eyeinsky/org-anki#49]
I might not be doing this right, but setting `org-anki-skip-function` doesn't seem to change the result of `org-anki-sync-all`. All entries get synchronized regardless.

The function I'm trying to use is this:
```
 (lambda ()
   (if (nth 2 (org-heading-components))
       (forward-line 1)
     nil)))
```
This is meant to skip headers with a TODO tag.

`org-anki-skip-function` looks like this:
```
(closure
 (t)
 nil
 (if
     (nth 2
          (org-heading-components))
     (forward-line 1)
   nil))
```
So it seems to be set correctly.

I test my skip function like this:
```
(defun test ()
  (let ((entries nil))
    (org-map-entries
     (lambda ()
       (push (org-heading-components) entries)
       (push "\n" entries))
     nil
     nil
     (lambda ()
       (if (nth 2 (org-heading-components))
           (forward-line 1)
         nil)))
    (print entries)))
```
And it does work as expected, printing only the entries I want.

The org file I tested this with looks like this:
```
* TODO not a card
* TODO also not a card
** an actual card
     content
```

All three headers end up being turned into cards.

**Comment by Elilif** [comment]
It seems `org-anki-skip-function` was quoted uncorrectly, the PR: https://github.com/eyeinsky/org-anki/pull/50 fixed that.

**Comment by eyeinsky** [comment]
Thanks @Elilif!

**Comment by nyxkn** [comment]
Sweet. Thanks!
