### ISSUE TITLE
cloze card with Extra at the back

### ISSUE THREAD

**Issue by basaran** [eyeinsky/org-anki#67]
Hello,

Could you elaborate please if creating such a card is possible?

```
* {{c1::mkinitcpio::x}} is a bash script
** Extra
    Indeed, it is a bash script and not a perl script.
```

It ends up creating two notes. I also tried making a custom model with `'org-anki-model-fields` but couldn't get far. I also tried like this:

```
* {{c1::mkinitcpio::x}} is a bash script
Indeed, it is a bash script and not a perl script.
```
and it creates one card, but the Extra is ignored. It doesn't reach Anki.

**Comment by eyeinsky** [comment]
It seems to be a bug, if you replace line 240 ```((org-anki--is-cloze title) `("Cloze" "Text" ,title))```
with ```((org-anki--is-cloze title) `("Cloze" "Text" ,title "Extra" ,content))``` and try this with your second example then it might work. Will fix this when I get some time (merge requests also welcome!).

**Comment by basaran** [comment]
That worked :)

I will end a PR tonight. Arigato.
