### ISSUE TITLE
Wrong type argument: proper-list-p, ("fields required" . fields)

### ISSUE THREAD

**Issue by Elilif** [eyeinsky/org-anki#69]
the following code in the function `org-anki--get-fields`:
```
(t (org-anki--report-error
           "org-anki--get-fields: %s"
           ,("fields required" . fields)
           ,("fields found" . found-fields)))
```
will cause a compiler error, and it seems that `org-anki--report-error` only accepts two arguments but there are three.

**Comment by eyeinsky** [comment]
Fixed in latest master b9a6ec16696a79c319131b8d683d4caae0be90d6, thanks! :)
