### ISSUE TITLE
how to add note with Cloze?

### ISSUE THREAD

**Issue by Prague2049** [eyeinsky/org-anki#74]
When I enter the following example in the org file, then M+x org-anki-sync-entry.
#+ANKI_DECK: org-anki-test-deck

hande
** * Q: Kaleida was funded to the tune of {{c1::$40 million::…amount}} by Apple Computer and IBM in 1991
there is a question: org-anki error: Couldn’t add note, received error: (model was not found: Cloze) ?

**Comment by Prague2049** [comment]
When I enter the following example in the org file, then M+x org-anki-sync-entry.
#+ANKI_DECK: org-anki-test-deck
* hande
** * Q: Kaleida was funded to the tune of {{c1::$40 million::…amount}} by Apple Computer and IBM in 1991
there is a question: org-anki error: Couldn’t add note, received error: (model was not found: Cloze) ?

**Comment by eyeinsky** [comment]
In your Anki app, if you go to Tools -> Manage Note Types, then do you see Cloze in the list?

**Comment by Prague2049** [comment]
Thanks! After I add fill in the Cloze in anki, the problem is solved.
How to create :ANKI_DECK: my-target-deck? Using org-anki-import-deck seems to only create #+ANKI_DECK: my-target-deck.

**Comment by eyeinsky** [comment]
Is "my-target-deck" an existing deck in the Anki app? `org-anki-import-deck` imports notes from Anki, while the other commands sync notes from org-mode to Anki -- which way are you trying to go?

**Comment by Prague2049** [comment]
I use many small org-roam files for note taking. If I want to generate a card with the contents of some org files, is it possible to use org-anki? When I use org-anki-import-deck in an org file, all other cards of my-target-deck will be exported to this file.

**Comment by eyeinsky** [comment]
Use either `org-anki-sync-entry`, `org-anki-sync-all`, `org-anki-update-all` to sync cards from org-mode to Anki. (`org-anki-import-deck` is for when you want to get *already existing cards* from Anki into org-mode.)

**Comment by eyeinsky** [comment]
You can set the default deck name globally with `(customize-set-variable 'org-anki-default-deck "my-target-deck")` in emacs (to any deck name you want, not just "my-target-deck").

This way you don't need to add `#+ANKI_DECK: my-target-deck` to every file.

**Comment by Prague2049** [comment]
Thanks!

**Comment by eyeinsky** [comment]
I'm closing this as done, but also adding a label "documentation", such that whenever I get to improving documentation I could find it.
