### ISSUE TITLE
Can images be included in content?

### ISSUE THREAD

**Issue by Prague2049** [eyeinsky/org-anki#75]
Can images be included in content? As follow:
* Test
:PROPERTIES:
:ANKI_NOTE_ID: 1690354020562
:END:
[[./img.png]]
Photos are not displayed in anki.

**Comment by eyeinsky** [comment]
Syncing images is not supported at the moment :(. There feature is being worked on here #43, but it's not done yet.

**Comment by eyeinsky** [comment]
I'm closing this as a duplicate of this issue: https://github.com/eyeinsky/org-anki/issues/17, let's discuss further there. :)
