### ISSUE TITLE
Special symbols throw error using org-anki-sync-entry

### ISSUE THREAD

**Issue by ajtfang** [eyeinsky/org-anki#76]
When using org-anki-sync-entry with an entry with a special character (for example an accented vowel), I get a the following message:

error in process sentinel: url-http-create-request: Multibyte text in HTTP request

Is there a workaround for this to sync entries with special characters?

**Comment by kenhuang-io** [comment]
Hi,

Why not paste in the exact entry here, so that folks can confirm if it's reproducible or not.

**Comment by ajtfang** [comment]
Turned out it was a problem on my end with my encoding!
