### ISSUE TITLE
Add configurable "end tag" to delimit entry content that gets set as card back

### ISSUE THREAD

**Issue by eyeinsky** [eyeinsky/org-anki#8]
```org
* Card front

Card back

--

Random text continues
```

In the previous org entry set title as card front, and everything up to the double-dash as card-back, leaving the rest alone. This allows to have org entries with long content without having all of it as card back. Otherwise one would need to create ad hoc subheading for anki.

**Comment by eyeinsky** [comment]
The "--" should be configurable.

**Comment by Charlie-Gordon** [comment]
I can see this happening by modifying `org-anki--entry-content-until-any-heading` with the `TO` argument of `buffer-substring-no-properties` being a marker of "end tag"  but, I think that "--" is far too common to be the default.

**Comment by eyeinsky** [comment]
Yup. I think I would have had a review of all the markup that org-mode uses -- to see what is "free". But perhaps even this isn't a good idea, so maybe not have any default at all, and have it set to `nil` (= custom end marker not present) and then make it possible to set it from either .emacs, file property or entry property (similar how it is for deck name). What do you think?

**Comment by Charlie-Gordon** [comment]
@eyeinsky 
Hello again, after some quick search in org's info node, I just found out about that org has comment! Check this out [Comment lines](https://orgmode.org/manual/Comment-Lines.html) so this means that content with # at the beginning will get ignore by your `org-anki--string-to-html` export function so please try calling `org-anki-sync-entry` on [this heading ](https://ghostbin.com/paste/9ruod) or 

```
** Card front
card back
# explaination for card back
# junk
# no
# what
# nonsensical
# lfjsd
# lksdjf;sjfjf
#+BEGIN_COMMENT
this is about card back
nonsense
don’t include this please
dlksjf
lsdjf yeah?
yeah uysdfsjlf
#+END_COMMENT

```
So without the "end tag", you can just `M-;` on the region you want to ignore and that's it!

Edit: messed up the formatting

**Comment by eyeinsky** [comment]
Thanks, using comments works to exclude content from being synced.
