### ISSUE TITLE
Multiline basic deck problem: Not enough arguments for format string

### ISSUE THREAD

**Issue by Ypot** [eyeinsky/org-anki#85]
Hi

I am trying to create a deck using `org-anki-sync-all` from this buffer:
https://paste.quest/?b6f061723eebffee#2gC8wUX73etbZz5Pobpcot9EgfFeutNdy3189QoceiRu

But I get this error message:
`org-anki--get-fields: Not enough arguments for format string`

How can I solve it?
Best regards

**Comment by eyeinsky** [comment]
Hi, I've pushed a fix for reporting the error better 05eed3539dda5303ba912abfc50e3be9d6811fe2 and bumped the minor version, could you try it whenever you have time? :)

**Comment by Ypot** [comment]
Tried and worked!
It took its time, but it worked
[TodosUnidos.txt](https://github.com/eyeinsky/org-anki/files/13480724/TodosUnidos.txt)
I'm adding a file just in case you wanted to try.

Thanks
