### ISSUE TITLE
Still depends on archived ox-slimhtml

### ISSUE THREAD

**Issue by tarsius** [eyeinsky/org-anki#9]
`org-anki` still depends on `ox-slimhtml` whose repository has been archived with this comment:

> slimhtml is now part of Org, included in GNU Emacs, future bug reports or contributions should be sent to Org directly.

I am not sure what that means. No file named `ox-slimhtml.el` appeared inside the Org or Emacs repositories, so I am guessing it means the functionality that `ox-slimhtml.el` used to provide has now been integrated into the `ox-html.el` that is part of Org. If that is so, then you should stop requiring `ox-slimhtml` and make other adjustments.

@balddotcat could you please provide some clarification. Preferably here and at the top of the readme file.

**Comment by eyeinsky** [comment]
@tarsius Thank you for the ping. Given `ox-slimhtml` is archived, will it be removed from melpa as well?

I can't really see either, where or how  `ox-slimhtml` has been integrated, but perhaps the `org-html` exporter in org-mode has now feature parity with slimhtml? Anyway, will give another shot to finding a way to use `org-html` instead.

**Comment by eyeinsky** [comment]
ff961616e52840b458cd24e2d04b43fc964737f7 will be merged soon, will this resolve this issue?

**Comment by tarsius** [comment]
I think so.

**Comment by eyeinsky** [comment]
@tarsius cool, merged that fix!
