### ISSUE TITLE
Importing a deck fails (wrong-type-argument stringp nil)

### ISSUE THREAD

**Issue by reflektoin** [eyeinsky/org-anki#92]
Hi,
Thank you for creating this package!

I ran into issue when importing a card from this deck:
https://ankiweb.net/shared/info/653061995.

org-anki-import-deck calls org-anki--write-note. Which then calls org-anki--parse-note. Somewhere here it might be that something goes wrong with fields.

I'll look into this more later but here's what's shown when Emacs entered debugger after I had executed "toggle-debug-on-error":

>Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  org-anki--multiline-front(nil)
  org-anki--write-note(#s(org-anki--note :maybe-id 1710104761787 :fields nil :tags nil :deck "IMPORT_TEST" :type "Memrise - 4000 German Words by Frequency" :point nil))
  #f(compiled-function (json) #<bytecode -0x3ef4dd2aee3877d>)(((noteId . 1710104761787) (tags . []) (fields (German (value . "deutsch") (order . 0)) (Sample\ sentence (value . "q") (order . 1)) (English (value . "german") (order . 2)) (English\ sentence (value . "q") (order . 3)) (Picture (value . "q") (order . 4)) (German\ Alternatives (value . "q") (order . 5)) (German\ Hidden\ Alternatives (value . "q") (order . 6)) (German\ Typing\ Corrects (value . "q") (order . 7)) (English\ Alternatives (value . "q") (order . 8)) (English\ Hidden\ Alternatives (value . "q") (order . 9)) (English\ Typing\ Corrects (value . "q") (order . 10)) (Plural\ and\ inflected\ forms (value . "q") (order . 11)) (Plural\ and\ inflected\ forms\ Alternatives (value . "q") (order . 12)) (Plural\ and\ inflected\ forms\ Hidden\ Alternatives (value . "q") (order . 13)) (Plural\ and\ inflected\ forms\ Typing\ Corrects (value . "q") (order . 14)) (Sample\ sentence\ Alternatives (value . "q") (order . 15)) (Sample\ sentence\ Hidden\ Alternatives (value . "q") (order . 16)) (Sample\ sentence\ Typing\ Corrects (value . "q") (order . 17)) (Part\ of\ Speech (value . "q") (order . 18)) (Audio (value . "") (order . 19)) (Level (value . "q") (order . 20)) (Thing (value . "q") (order . 21))) (modelName . "Memrise - 4000 German Words by Frequency") (cards . [1710104761788 1710104761789])))
  mapc(#f(compiled-function (json) #<bytecode -0x3ef4dd2aee3877d>) [((noteId . 1710104761787) (tags . []) (fields (German (value . "deutsch") (order . 0)) (Sample\ sentence (value . "q") (order . 1)) (English (value . "german") (order . 2)) (English\ sentence (value . "q") (order . 3)) (Picture (value . "q") (order . 4)) (German\ Alternatives (value . "q") (order . 5)) (German\ Hidden\ Alternatives (value . "q") (order . 6)) (German\ Typing\ Corrects (value . "q") (order . 7)) (English\ Alternatives (value . "q") (order . 8)) (English\ Hidden\ Alternatives (value . "q") (order . 9)) (English\ Typing\ Corrects (value . "q") (order . 10)) (Plural\ and\ inflected\ forms (value . "q") (order . 11)) (Plural\ and\ inflected\ forms\ Alternatives (value . "q") (order . 12)) (Plural\ and\ inflected\ forms\ Hidden\ Alternatives (value . "q") (order . 13)) (Plural\ and\ inflected\ forms\ Typing\ Corrects (value . "q") (order . 14)) (Sample\ sentence\ Alternatives (value . "q") (order . 15)) (Sample\ sentence\ Hidden\ Alternatives (value . "q") (order . 16)) (Sample\ sentence\ Typing\ Corrects (value . "q") (order . 17)) (Part\ of\ Speech (value . "q") (order . 18)) (Audio (value . "") (order . 19)) (Level (value . "q") (order . 20)) (Thing (value . "q") (order . 21))) (modelName . "Memrise - 4000 German Words by Frequency") (cards . [1710104761788 1710104761789]))])
  #f(compiled-function (the-result) #<bytecode 0x15c3827f40e02cde>)([((noteId . 1710104761787) (tags . []) (fields (German (value . "deutsch") (order . 0)) (Sample\ sentence (value . "q") (order . 1)) (English (value . "german") (order . 2)) (English\ sentence (value . "q") (order . 3)) (Picture (value . "q") (order . 4)) (German\ Alternatives (value . "q") (order . 5)) (German\ Hidden\ Alternatives (value . "q") (order . 6)) (German\ Typing\ Corrects (value . "q") (order . 7)) (English\ Alternatives (value . "q") (order . 8)) (English\ Hidden\ Alternatives (value . "q") (order . 9)) (English\ Typing\ Corrects (value . "q") (order . 10)) (Plural\ and\ inflected\ forms (value . "q") (order . 11)) (Plural\ and\ inflected\ forms\ Alternatives (value . "q") (order . 12)) (Plural\ and\ inflected\ forms\ Hidden\ Alternatives (value . "q") (order . 13)) (Plural\ and\ inflected\ forms\ Typing\ Corrects (value . "q") (order . 14)) (Sample\ sentence\ Alternatives (value . "q") (order . 15)) (Sample\ sentence\ Hidden\ Alternatives (value . "q") (order . 16)) (Sample\ sentence\ Typing\ Corrects (value . "q") (order . 17)) (Part\ of\ Speech (value . "q") (order . 18)) (Audio (value . "") (order . 19)) (Level (value . "q") (order . 20)) (Thing (value . "q") (order . 21))) (modelName . "Memrise - 4000 German Words by Frequency") (cards . [1710104761788 1710104761789]))])
  #f(compiled-function (&rest rest) #<bytecode 0x5d47cc817086f55>)(:data ((result . [((noteId . 1710104761787) (tags . []) (fields (German (value . "deutsch") (order . 0)) (Sample\ sentence (value . "q") (order . 1)) (English (value . "german") (order . 2)) (English\ sentence (value . "q") (order . 3)) (Picture (value . "q") (order . 4)) (German\ Alternatives (value . "q") (order . 5)) (German\ Hidden\ Alternatives (value . "q") (order . 6)) (German\ Typing\ Corrects (value . "q") (order . 7)) (English\ Alternatives (value . "q") (order . 8)) (English\ Hidden\ Alternatives (value . "q") (order . 9)) (English\ Typing\ Corrects (value . "q") (order . 10)) (Plural\ and\ inflected\ forms (value . "q") (order . 11)) (Plural\ and\ inflected\ forms\ Alternatives (value . "q") (order . 12)) (Plural\ and\ inflected\ forms\ Hidden\ Alternatives (value . "q") (order . 13)) (Plural\ and\ inflected\ forms\ Typing\ Corrects (value . "q") (order . 14)) (Sample\ sentence\ Alternatives (value . "q") (order . 15)) (Sample\ sentence\ Hidden\ Alternatives (value . "q") (order . 16)) (Sample\ sentence\ Typing\ Corrects (value . "q") (order . 17)) (Part\ of\ Speech (value . "q") (order . 18)) (Audio (value . "") (order . 19)) (Level (value . "q") (order . 20)) (Thing (value . "q") (order . 21))) (modelName . "Memrise - 4000 German Words by Frequency") (cards . [1710104761788 1710104761789]))]) (error)) :symbol-status success :error-thrown nil :response #s(request-response :status-code 200 :history nil :data ((result . [((noteId . 1710104761787) (tags . []) (fields (German ... ...) (Sample\ sentence ... ...) (English ... ...) (English\ sentence ... ...) (Picture ... ...) (German\ Alternatives ... ...) (German\ Hidden\ Alternatives ... ...) (German\ Typing\ Corrects ... ...) (English\ Alternatives ... ...) (English\ Hidden\ Alternatives ... ...) (English\ Typing\ Corrects ... ...) (Plural\ and\ inflected\ forms ... ...) (Plural\ and\ inflected\ forms\ Alternatives ... ...) (Plural\ and\ inflected\ forms\ Hidden\ Alternatives ... ...) (Plural\ and\ inflected\ forms\ Typing\ Corrects ... ...) (Sample\ sentence\ Alternatives ... ...) (Sample\ sentence\ Hidden\ Alternatives ... ...) (Sample\ sentence\ Typing\ Corrects ... ...) (Part\ of\ Speech ... ...) (Audio ... ...) (Level ... ...) (Thing ... ...)) (modelName . "Memrise - 4000 German Words by Frequency") (cards . [1710104761788 1710104761789]))]) (error)) :error-thrown nil :symbol-status success :url "http://127.0.0.1:8765/" :done-p nil :settings (:type "GET" :data "{\"version\":6,\"action\":\"notesInfo\",\"params\":{\"notes..." :headers (("Content-Type" . "application/json")) :parser json-read :error #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_21> :success #f(compiled-function (&rest rest) #<bytecode 0x5d47cc817086f55>) :url "http://127.0.0.1:8765" :response #8 :encoding utf-8) :-buffer #<killed buffer> :-raw-header "HTTP/1.1 200 OK\nContent-Type: application/json\nAcc..." :-timer nil :-backend curl))
  apply(#f(compiled-function (&rest rest) #<bytecode 0x5d47cc817086f55>) (:data ((result . [((noteId . 1710104761787) (tags . []) (fields (German ... ...) (Sample\ sentence ... ...) (English ... ...) (English\ sentence ... ...) (Picture ... ...) (German\ Alternatives ... ...) (German\ Hidden\ Alternatives ... ...) (German\ Typing\ Corrects ... ...) (English\ Alternatives ... ...) (English\ Hidden\ Alternatives ... ...) (English\ Typing\ Corrects ... ...) (Plural\ and\ inflected\ forms ... ...) (Plural\ and\ inflected\ forms\ Alternatives ... ...) (Plural\ and\ inflected\ forms\ Hidden\ Alternatives ... ...) (Plural\ and\ inflected\ forms\ Typing\ Corrects ... ...) (Sample\ sentence\ Alternatives ... ...) (Sample\ sentence\ Hidden\ Alternatives ... ...) (Sample\ sentence\ Typing\ Corrects ... ...) (Part\ of\ Speech ... ...) (Audio ... ...) (Level ... ...) (Thing ... ...)) (modelName . "Memrise - 4000 German Words by Frequency") (cards . [1710104761788 1710104761789]))]) (error)) :symbol-status success :error-thrown nil :response #s(request-response :status-code 200 :history nil :data ((result . [((noteId . 1710104761787) (tags . ...) (fields ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (modelName . "Memrise - 4000 German Words by Frequency") (cards . ...))]) (error)) :error-thrown nil :symbol-status success :url "http://127.0.0.1:8765/" :done-p nil :settings (:type "GET" :data "{\"version\":6,\"action\":\"notesInfo\",\"params\":{\"notes..." :headers (("Content-Type" . "application/json")) :parser json-read :error #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_21> :success #f(compiled-function (&rest rest) #<bytecode 0x5d47cc817086f55>) :url "http://127.0.0.1:8765" :response #10 :encoding utf-8) :-buffer #<killed buffer> :-raw-header "HTTP/1.1 200 OK\nContent-Type: application/json\nAcc..." :-timer nil :-backend curl)))
  request--callback(#<killed buffer> :type "GET" :data "{\"version\":6,\"action\":\"notesInfo\",\"params\":{\"notes..." :headers (("Content-Type" . "application/json")) :parser json-read :error #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_21> :success #f(compiled-function (&rest rest) #<bytecode 0x5d47cc817086f55>) :url "http://127.0.0.1:8765" :response #s(request-response :status-code 200 :history nil :data ((result . [((noteId . 1710104761787) (tags . []) (fields (German ... ...) (Sample\ sentence ... ...) (English ... ...) (English\ sentence ... ...) (Picture ... ...) (German\ Alternatives ... ...) (German\ Hidden\ Alternatives ... ...) (German\ Typing\ Corrects ... ...) (English\ Alternatives ... ...) (English\ Hidden\ Alternatives ... ...) (English\ Typing\ Corrects ... ...) (Plural\ and\ inflected\ forms ... ...) (Plural\ and\ inflected\ forms\ Alternatives ... ...) (Plural\ and\ inflected\ forms\ Hidden\ Alternatives ... ...) (Plural\ and\ inflected\ forms\ Typing\ Corrects ... ...) (Sample\ sentence\ Alternatives ... ...) (Sample\ sentence\ Hidden\ Alternatives ... ...) (Sample\ sentence\ Typing\ Corrects ... ...) (Part\ of\ Speech ... ...) (Audio ... ...) (Level ... ...) (Thing ... ...)) (modelName . "Memrise - 4000 German Words by Frequency") (cards . [1710104761788 1710104761789]))]) (error)) :error-thrown nil :symbol-status success :url "http://127.0.0.1:8765/" :done-p nil :settings (:type "GET" :data "{\"version\":6,\"action\":\"notesInfo\",\"params\":{\"notes..." :headers (("Content-Type" . "application/json")) :parser json-read :error #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_21> :success #f(compiled-function (&rest rest) #<bytecode 0x5d47cc817086f55>) :url "http://127.0.0.1:8765" :response #17 :encoding utf-8) :-buffer #<killed buffer> :-raw-header "HTTP/1.1 200 OK\nContent-Type: application/json\nAcc..." :-timer nil :-backend curl) :encoding utf-8)
  apply(request--callback #<killed buffer> (:type "GET" :data "{\"version\":6,\"action\":\"notesInfo\",\"params\":{\"notes..." :headers (("Content-Type" . "application/json")) :parser json-read :error #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_21> :success #f(compiled-function (&rest rest) #<bytecode 0x5d47cc817086f55>) :url "http://127.0.0.1:8765" :response #s(request-response :status-code 200 :history nil :data ((result . [((noteId . 1710104761787) (tags . ...) (fields ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (modelName . "Memrise - 4000 German Words by Frequency") (cards . ...))]) (error)) :error-thrown nil :symbol-status success :url "http://127.0.0.1:8765/" :done-p nil :settings #3 :-buffer #<killed buffer> :-raw-header "HTTP/1.1 200 OK\nContent-Type: application/json\nAcc..." :-timer nil :-backend curl) :encoding utf-8))
  request--curl-callback("http://127.0.0.1:8765" #<process request curl> "finished\n")
  apply(request--curl-callback ("http://127.0.0.1:8765" #<process request curl> "finished\n"))
  #f(compiled-function (&rest args2) #<bytecode -0x19fdbe572f15e1b9>)(#<process request curl> "finished\n")
`

**Comment by kenhuang-io** [comment]
Hi,

From your stacktrace, we can see that it's because this deck has an unusual model name called `"Memrise - 4000 German Words by Frequency"`, and it's not configured in `org-anki-model-fields` by default.

Depends on what fields you want to include, you can add them to that variable, for example,

```
(add-to-list 'org-anki-model-fields (list
                                     "Memrise - 4000 German Words by Frequency" ; model name
                                     ;; fields to export
                                     "German"
                                     "German sentence"
                                     "English"
                                     "English sentence"))
```

Below are all the fields in your error stack (you can also find them in the first column of the table in the anki web page), pick the ones that make sense for you:

```
(fields (German (value . "deutsch") (order . 0))
        (Sample\ sentence (value . "q") (order . 1))
        (English (value . "german") (order . 2))
        (English\ sentence (value . "q") (order . 3))
        (Picture (value . "q") (order . 4))
        (German\ Alternatives (value . "q") (order . 5))
        (German\ Hidden\ Alternatives (value . "q") (order . 6))
        (German\ Typing\ Corrects (value . "q") (order . 7))
        (English\ Alternatives (value . "q") (order . 8))
        (English\ Hidden\ Alternatives (value . "q") (order . 9))
        (English\ Typing\ Corrects (value . "q") (order . 10))
        (Plural\ and\ inflected\ forms (value . "q") (order . 11))
        (Plural\ and\ inflected\ forms\ Alternatives (value . "q") (order . 12))
        (Plural\ and\ inflected\ forms\ Hidden\ Alternatives (value . "q") (order . 13))
        (Plural\ and\ inflected\ forms\ Typing\ Corrects (value . "q") (order . 14))
        (Sample\ sentence\ Alternatives (value . "q") (order . 15))
        (Sample\ sentence\ Hidden\ Alternatives (value . "q") (order . 16))
        (Sample\ sentence\ Typing\ Corrects (value . "q") (order . 17))
        (Part\ of\ Speech (value . "q") (order . 18))
        (Audio (value . "") (order . 19))
        (Level (value . "q") (order . 20))
        (Thing (value . "q") (order . 21)))
```

**Comment by reflektoin** [comment]
@whatacold Thank you a lot for the quick reply, I got it working with your help!

**Comment by kenhuang-io** [comment]
Glad it works!
